---
- id: helm-diagrams
  name: Generate Helm Diagrams
  description: |
      This hook generate helm diagrams using KubeDiagrams
  entry: helm-diagrams
  language: python
  always_run: true
  files: ^chart/.*\.ya?ml$
  pass_filenames: false
  args:
    - chart
    - --output
    - chart/chart-diagram.png
    - --include-crds=true
